export const itemOptions = [
  {
    _id: "1",
    name: "assorted cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_1.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "2",
    name: "monster cupcake",
    price: "$30.00",
    url: new URL("../Assets/images/Snacks_2.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "3",
    name: "Reeses cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_3.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "4",
    name: "oreo cupcake",
    price: "$25.00",
    url: new URL("../Assets/images/Snacks_4.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "5",
    name: "Italian cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_5.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "6",
    name: "fancy chocolate cookie",
    price: "$20.00",
    url: new URL("../Assets/images/Snacks_6.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "7",
    name: "Valentine gift set",
    price: "$50.00",
    url: new URL("../Assets/images/Snacks_7.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "8",
    name: "sundae cookie",
    price: "$30.00",
    url: new URL("../Assets/images/Snacks_8.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "9",
    name: "pop-tart cookie",
    price: "$20.00",
    url: new URL("../Assets/images/Snacks_9.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "10",
    name: "champagne cupcake",
    price: "$30.00",
    url: new URL("../Assets/images/Snacks_10.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "11",
    name: "sports fan cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_11.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "12",
    name: "Phyllis blueberry cookie",
    price: "$30.00",
    url: new URL("../Assets/images/Snacks_12.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "13",
    name: "M&M cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_13.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "14",
    name: "Rainbow cupcake",
    price: "$45.00",
    url: new URL("../Assets/images/Snacks_14.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "15",
    name: "Choco chip cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_15.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "16",
    name: "Rainbow cookie",
    price: "$25.00",
    url: new URL("../Assets/images/Snacks_16.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "17",
    name: "Lion cupcake",
    price: "$40.00",
    url: new URL("../Assets/images/Snacks_18.jpg", import.meta.url).href,
    category: "cupcake ",
  },
  {
    _id: "18",
    name: "Rainbow jelly cookie",
    price: "$30.00",
    url: new URL("../Assets/images/Snacks_19.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "19",
    name: "Blue cookie",
    price: "$15.00",
    url: new URL("../Assets/images/Snacks_20.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "20",
    name: "Sprinkle cookie",
    price: "$25.00",
    url: new URL("../Assets/images/Snacks_21.jpg", import.meta.url).href,
    category: "cookie",
  },
  {
    _id: "21",
    name: "Choco sprinkle cookie",
    price: "$25.00",
    url: new URL("../Assets/images/Snacks_22.jpg", import.meta.url).href,
    category: "cookie",
  },
];

export const slides = [
  {
    name: "slide-one",
    url: new URL("../Assets/images/Snacks_18.jpg", import.meta.url).href,
    alt: "Lion Cupcake",
  },
  {
    name: "slide-two",
    url: new URL("../Assets/images/Snacks_2.jpg", import.meta.url).href,
    alt: "Monster Cupcake",
  },
  {
    name: "slide-three",
    url: new URL("../Assets/images/Snacks_3.jpg", import.meta.url).href,
    alt: "Reeses Cookie",
  },
  {
    name: "slide-four",
    url: new URL("../Assets/images/Snacks_10.jpg", import.meta.url).href,
    alt: "Champagne Cupcake",
  },
  {
    name: "slide-five",
    url: new URL("../Assets/images/Snacks_4.jpg", import.meta.url).href,
    alt: "Oreo Cupcake",
  },
];
